all:
	# lldb -- 
	/Users/penny/shunting/llvm-project/build/bin/clang -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib sum.c
